from tasks.prequential import Prequential
from tasks.prequential_drift import PrequentialDrift
from tasks.prequential_drift_evaluator import PrequentialDriftEvaluator
from tasks.prequential_learner_detector_pairs import PrequentialMultiPairs